# Site settings
title: eviloctopus
email: yratof@gmail.com
description: Games
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eviloctopus.co.uk" # the base hostname & protocol for your site
permalink: /:year/:month/:title/
twitter_username: eviloctopus
github_username:  yratof
timezone: Europe/Oslo

# Extra things
exclude: [ 'node_modules', 'post', 'animation', 'illustration' ]

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap